<?php

return [

    'groups' => [
        'overview' => 'Overview',
        'content' => 'Content & Forms',
        'frontend' => 'Frontend Settings',
        'growth' => 'Growth',
        'backend' => 'Backend Settings',
    ],

    /*
    |--------------------------------------------------------------------------
    | Module catalog
    |--------------------------------------------------------------------------
    |
    | This catalog is the source of truth for modules and permissions.
    | `php artisan permissions:sync` upserts it into the database. Routes
    | should authorize with the permission slugs declared here ({slug}.{action}).
    |
    */

    'catalog' => [
        'dashboard' => [
            'name' => 'Dashboard',
            'description' => 'Workspace overview and recent activity.',
            'group' => 'overview',
            'icon' => 'grid',
            'sort_order' => 10,
            'is_core' => true,
            'implemented' => true,
            'route' => 'tenant.dashboard',
            'nav_permission' => null,
            'actions' => [],
        ],
        'users' => [
            'name' => 'Users',
            'description' => 'Invite and manage people in this workspace.',
            'group' => 'backend',
            'icon' => 'users',
            'sort_order' => 20,
            'is_core' => true,
            'implemented' => true,
            'route' => 'tenant.users.index',
            'nav_permission' => 'users.view',
            'actions' => [
                'view' => 'View',
                'create' => 'Create',
                'edit' => 'Edit',
                'delete' => 'Delete',
            ],
        ],
        'roles' => [
            'name' => 'Roles',
            'description' => 'Create roles and assign what each role can do.',
            'group' => 'backend',
            'icon' => 'shield',
            'sort_order' => 30,
            'is_core' => true,
            'implemented' => true,
            'route' => 'tenant.roles.index',
            'nav_permission' => 'roles.view',
            'actions' => [
                'view' => 'View',
                'create' => 'Create',
                'edit' => 'Edit',
                'delete' => 'Delete',
            ],
        ],
        'permissions' => [
            'name' => 'Permissions',
            'description' => 'Review the permission catalog for enabled modules.',
            'group' => 'backend',
            'icon' => 'key',
            'sort_order' => 40,
            'is_core' => true,
            'implemented' => true,
            'route' => 'tenant.permissions.index',
            'nav_permission' => 'permissions.view',
            'actions' => [
                'view' => 'View',
            ],
        ],
        'categories' => [
            'name' => 'Categories',
            'description' => 'Group content into configurable categories.',
            'group' => 'content',
            'icon' => 'folder',
            'sort_order' => 50,
            'is_core' => false,
            'implemented' => true,
            'route' => 'tenant.categories.index',
            'nav_permission' => 'categories.view',
            'actions' => [
                'view' => 'View',
                'create' => 'Create',
                'edit' => 'Edit',
                'delete' => 'Delete',
            ],
        ],
        'posts' => [
            'name' => 'Posts',
            'description' => 'Dynamic posts such as articles, tools, products, and resources.',
            'group' => 'content',
            'icon' => 'document',
            'sort_order' => 60,
            'is_core' => false,
            'implemented' => true,
            'route' => 'tenant.posts.index',
            'nav_permission' => 'posts.view',
            'actions' => [
                'view' => 'View',
                'create' => 'Create',
                'edit' => 'Edit',
                'delete' => 'Delete',
                'publish' => 'Publish',
                'types' => 'Manage types',
            ],
        ],
        'media' => [
            'name' => 'Media',
            'description' => 'Upload and reuse images and files.',
            'group' => 'content',
            'icon' => 'photo',
            'sort_order' => 70,
            'is_core' => false,
            'implemented' => true,
            'route' => 'tenant.media.index',
            'nav_permission' => 'media.view',
            'actions' => [
                'view' => 'View',
                'create' => 'Create',
                'edit' => 'Edit',
                'delete' => 'Delete',
            ],
        ],
        'pages' => [
            'name' => 'Pages',
            'description' => 'Static and composed pages.',
            'group' => 'content',
            'icon' => 'layout',
            'sort_order' => 80,
            'is_core' => false,
            'implemented' => true,
            'route' => 'tenant.pages.index',
            'nav_permission' => 'pages.view',
            'actions' => [
                'view' => 'View',
                'create' => 'Create',
                'edit' => 'Edit',
                'delete' => 'Delete',
                'publish' => 'Publish',
            ],
        ],
        'form-builder' => [
            'name' => 'Form Builder',
            'description' => 'Build forms without hard-coded fields.',
            'group' => 'content',
            'icon' => 'form',
            'sort_order' => 90,
            'is_core' => false,
            'implemented' => true,
            'route' => 'tenant.form-builder.index',
            'nav_permission' => 'form-builder.view',
            'actions' => [
                'view' => 'View',
                'create' => 'Create',
                'edit' => 'Edit',
                'delete' => 'Delete',
            ],
        ],
        'layout-builder' => [
            'name' => 'Layout Builder',
            'description' => 'Arrange sections and layouts for content types.',
            'group' => 'frontend',
            'icon' => 'layout',
            'sort_order' => 100,
            'is_core' => false,
            'implemented' => true,
            'route' => 'tenant.layout.index',
            'nav_permission' => 'layout-builder.view',
            'actions' => [
                'view' => 'View',
                'create' => 'Create',
                'edit' => 'Edit',
                'delete' => 'Delete',
            ],
        ],
        'menu-manager' => [
            'name' => 'Menu Manager',
            'description' => 'Manage navigation menus.',
            'group' => 'frontend',
            'icon' => 'menu',
            'sort_order' => 110,
            'is_core' => false,
            'implemented' => true,
            'route' => 'tenant.menus.index',
            'nav_permission' => 'menu-manager.view',
            'actions' => [
                'view' => 'View',
                'create' => 'Create',
                'edit' => 'Edit',
                'delete' => 'Delete',
            ],
        ],
        'header-footer' => [
            'name' => 'Header / Footer',
            'description' => 'Configure the site header and footer.',
            'group' => 'frontend',
            'icon' => 'layout',
            'sort_order' => 120,
            'is_core' => false,
            'implemented' => true,
            'route' => 'tenant.header.edit',
            'nav_permission' => 'header-footer.view',
            'actions' => [
                'view' => 'View',
                'update' => 'Update',
            ],
        ],
        'theme-settings' => [
            'name' => 'Theme Settings',
            'description' => 'Colors, logo treatment, and theme options.',
            'group' => 'frontend',
            'icon' => 'paint',
            'sort_order' => 130,
            'is_core' => false,
            'implemented' => true,
            'route' => 'tenant.theme.edit',
            'nav_permission' => 'theme-settings.view',
            'actions' => [
                'view' => 'View',
                'update' => 'Update',
            ],
        ],
        'seo' => [
            'name' => 'SEO',
            'description' => 'Search titles, descriptions, and sharing defaults.',
            'group' => 'growth',
            'icon' => 'search',
            'sort_order' => 140,
            'is_core' => false,
            'implemented' => true,
            'route' => 'tenant.seo.edit',
            'nav_permission' => 'seo.view',
            'actions' => [
                'view' => 'View',
                'update' => 'Update',
            ],
        ],
        'analytics' => [
            'name' => 'Analytics',
            'description' => 'Traffic and content performance.',
            'group' => 'growth',
            'icon' => 'chart',
            'sort_order' => 150,
            'is_core' => false,
            'implemented' => true,
            'route' => 'tenant.analytics.edit',
            'nav_permission' => 'analytics.view',
            'actions' => [
                'view' => 'View',
                'update' => 'Update',
            ],
        ],
        'email' => [
            'name' => 'Email',
            'description' => 'Workspace email templates and delivery options.',
            'group' => 'growth',
            'icon' => 'mail',
            'sort_order' => 160,
            'is_core' => false,
            'implemented' => true,
            'route' => 'tenant.email.edit',
            'nav_permission' => 'email.view',
            'actions' => [
                'view' => 'View',
                'update' => 'Update',
            ],
        ],
        'feedback' => [
            'name' => 'Feedback',
            'description' => 'Messages submitted from the public site.',
            'group' => 'growth',
            'icon' => 'chat',
            'sort_order' => 170,
            'is_core' => false,
            'implemented' => true,
            'route' => 'tenant.feedback.index',
            'nav_permission' => 'feedback.view',
            'actions' => [
                'view' => 'View',
                'update' => 'Update',
                'delete' => 'Delete',
            ],
        ],
        'commerce' => [
            'name' => 'Commerce settings',
            'description' => 'Cart, checkout, and payment gateway settings. Customers and orders are under WooCommerce.',
            'group' => 'backend',
            'icon' => 'cart',
            'sort_order' => 175,
            'is_core' => false,
            'implemented' => true,
            'route' => 'tenant.commerce.edit',
            'nav_permission' => 'commerce.view',
            'actions' => [
                'view' => 'View',
                'update' => 'Update',
            ],
        ],
        'backup' => [
            'name' => 'Backup',
            'description' => 'Workspace export. Platform database backups stay with the super admin.',
            'group' => 'backend',
            'icon' => 'archive',
            'sort_order' => 180,
            'is_core' => false,
            'implemented' => true,
            'route' => 'tenant.backups.index',
            'nav_permission' => 'backup.view',
            'actions' => [
                'view' => 'View',
                'create' => 'Create',
                'download' => 'Download',
                'delete' => 'Delete',
            ],
        ],
        'settings' => [
            'name' => 'Settings',
            'description' => 'Workspace profile and preferences.',
            'group' => 'backend',
            'icon' => 'cog',
            'sort_order' => 190,
            'is_core' => true,
            'implemented' => true,
            'route' => 'tenant.settings.edit',
            'nav_permission' => 'settings.view',
            'actions' => [
                'view' => 'View',
                'update' => 'Update',
            ],
        ],
    ],

];
